### ISSUE TITLE
Can you please add a LICENSE and README file to this repository?

### ISSUE THREAD

**Issue by mithro** [negge/jpeg_gpu#3]
Hi!

This looks like an awesome project but doesn't seem to have any licensing information. I'm assuming this stuff is under an FOSS license as you work at Mozilla, but it would be good to know the exact details...

Thanks!

Tim 'mithro' Ansell
PS I would dump the text from your recent LCA talk proposal on this code into a README here too.

**Comment by negge** [comment]
Done, thanks for your interest.

**Comment by mithro** [comment]
Thanks, seems like a really cool project!
